import Link from "next/link";
import PageTitle from "../components/page-title";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog page: Spin a yarn, a spider's tale",
  description: "Generated by create next app",
};

export default function Blog() {
  return (
    <main className="block">
      <PageTitle text="Charlotte's blog" />
      <Link href="./blog/blog-one" className="block mt-10 mb-2">
        <span className="mb-2 underline">Wilbur: more than just Some Pig</span>
        <p className="my-2">
          Wilbur, my closest friend, is an incredible creature who embodies the
          virtues of loyalty, courage, and friendship. His warm spirit and
          eagerness for life inspire me daily. This is a story of how he
          transformed from an ordinary piglet into a beacon of hope for many.
        </p>
      </Link>

      <Link href="./blog/blog-two" className="mb-2 block">
        <span className="mb-2 underline">
          The extraordinary friends on the Zuckerman farm
        </span>
        <p className="my-2">
          Life on the Zuckerman farm is never dull with a cast of vibrant
          characters such as Templeton the Rat, the sweet and intelligent goose,
          and, of course, our leading swine, Wilbur. This post explores the
          unique personalities and hidden depths of our barnyard companions.
        </p>
      </Link>

      <Link href="./blog/blog-two" className="mb-2 block">
        <span className="mb-2 underline">The art of weaving words</span>
        <p className="my-2">
          From the delicate art of spinning silk to the intricacies of etching
          words on a web, this blog post delves into my fascinating world. Join
          me as I share some of my favorite words and the special meanings they
          hold.
        </p>
      </Link>
    </main>
  );
}
