import PageTitle from "../components/page-title";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About page: Spin a yarn, a spider's tale",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main className="block">
      <PageTitle text="About Charlotte" />
      <p className="mt-10 mb-2">
        Welcome to my &quot;About&quot; page! I am Charlotte, the creator and
        curator of this virtual web of wonder. By nature, I am a spinner, a
        weaver of silk and stories. You might know me from the barn at the
        Zuckerman farm, where I&apos;ve spun many a tale on my humble web.
      </p>
      <p className="mb-2">
        I believe that everyone and everything has a story to tell. My goal here
        is to shine a light on these stories, much like how I illuminated my
        dear friend Wilbur&apos;s tale. Though I am but a small grey spider, my
        mission is to celebrate the beauty and wonder in the world around us.
      </p>
      <p className="mb-2">
        In this web-space, I hope to weave tales of kindness, compassion, and
        bravery, just as I do on my spiderweb at the barn. I hope you&apos;ll
        find warmth and joy in these stories, just as Wilbur and I did.
      </p>
    </main>
  );
}
