import PageTitle from "../../components/page-title";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog number three: The art of weaving words",
  description: "Generated by create next app",
};

export default function BlogThree() {
  return (
      <main className="block">
        <PageTitle text="The art of weaving words" />
        <p className="mt-10 mb-2">
          From the delicate art of spinning silk to the intricacies of etching
          words on a web, this blog post delves into my fascinating world. Join
          me as I share some of my favorite words and the special meanings they
          hold.
        </p>
      </main>
  );
}
